---
title: "README.md"
output: html_document
date: "2024-10-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## International Trade and Pollution Analysis

This project was part of a CSS Bootcamp, where we explored the relationship between international trade and pollution. The primary goal of this analysis was to investigate how increases in trade impact CO2 emissions and other environmental factors.

## Project Overview

As globalization accelerates and international trade expands, the environmental consequences an area of concern. Utilizing data from the Quality of Government (QoG) dataset, this project delves into the correlation between trade volumes and pollution, with a particular focus on CO2 emissions as a marker of environmental degradation.

### Key Insights

1.  **Trade and CO2 Emissions**: This analysis demonstrates that as trade between nations increases, so do CO2 emissions. This finding suggests that while trade fosters economic growth and cooperation, it also contributes significantly to environmental harm. CO2 emissions, a potent greenhouse gas, play a central role in global warming and are one of the primary indicators of human-driven climate change.

2.  **CO2 as an Indicator of Pollution**: While CO2 emissions provide a clear marker of pollution, they do not tell the full story. There are other pollutants, and environmental impacts that also result from increased trade activities. A more comprehensive analysis of trade-related pollution should account for these additional factors to offer a fuller picture of the environmental consequences.

3.  **Trade and Climate Legislation**: Interestingly, these findings suggest that nations with higher levels of trade tend to adopt more climate-related laws and regulations. This may indicate that increased awareness of trade’s environmental impacts prompts governments to implement stricter environmental policies.
